// Generated by CoffeeScript 1.10.0
(function() {
  var countChar, isEven;

  isEven = function(n) {
    if (n === 0) {
      return "pair";
    }
    if (n === 1) {
      return "impair";
    }
    return isEven(n - 2);
  };

  console.log(isEven(18));

  countChar = function(chaine, char) {
    var i, j, ref, total;
    total = 0;
    for (i = j = 0, ref = chaine.length - 1; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
      if ((chaine.charAt(i)) === char) {
        total++;
      }
    }
    return total;
  };

  console.log(countChar("BBC", "B"));

  console.log(countChar("kakkolak", "k"));

}).call(this);
